[package]
name = "lish"
version = "0.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
rustyline = "*"
libc = "*"
regex = "*"

[dependencies.nom]
version = "*"
features = ["regexp"]
