#!/usr/bin/env python

import sys
import os
from subprocess import Popen, PIPE

test_file_name = sys.argv[1]

main_binary=os.path.join(os.getcwd(), "lish")
fixtures_dir = os.path.join(os.getcwd(), "tests/fixtures")

process = Popen([main_binary], stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=fixtures_dir)

stdout = process.stdout
stdin = process.stdin

failed = 0

for line in open(test_file_name):
    # empty lines
    if len(line.strip()) == 0:
        continue

    # description
    if line.startswith(";;"):
        continue

    # assertions
    if line.startswith(";=>"):
        expected = line[3:].strip()
        actual = stdout.readline().strip()

        if expected != actual:
            failed += 1

            print
            print "Test failed"
            print "Expected: " + expected
            print "Actual:   " + actual
            print

        continue

    # input
    stdin.write(line)

process.kill()

if failed > 0:
    sys.exit(1)
